
--
-- Zlib
--

zlib_public = {
	"thirdparty/zlib/zconf.h",
	"thirdparty/zlib/zlib.h"
}

zlib_sources = {
	"thirdparty/zlib/adler32.c",
	"thirdparty/zlib/compress.c",
	"thirdparty/zlib/crc32.c",
	"thirdparty/zlib/crc32.h",
	"thirdparty/zlib/deflate.c",
	"thirdparty/zlib/deflate.h",
	"thirdparty/zlib/gzclose.c",
	"thirdparty/zlib/gzguts.h",
	"thirdparty/zlib/gzlib.c",
	"thirdparty/zlib/gzread.c",
	"thirdparty/zlib/gzwrite.c",
	"thirdparty/zlib/infback.c",
	"thirdparty/zlib/inffast.c",
	"thirdparty/zlib/inffast.h",
	"thirdparty/zlib/inffixed.h",
	"thirdparty/zlib/inflate.c",
	"thirdparty/zlib/inflate.h",
	"thirdparty/zlib/inftrees.c",
	"thirdparty/zlib/inftrees.h",
	"thirdparty/zlib/trees.c",
	"thirdparty/zlib/trees.h",
	"thirdparty/zlib/uncompr.c",
	"thirdparty/zlib/zutil.c",
	"thirdparty/zlib/zutil.h"
}

--
-- LibPNG
--

libpng_public = {
	"thirdparty/libpng/png.h",
	"thirdparty/libpng/pngconf.h"
}

libpng_sources = {
	"thirdparty/libpng/png.c",
	"thirdparty/libpng/pngpriv.h",
	"thirdparty/libpng/pngstruct.h",
	"thirdparty/libpng/pnginfo.h",
	"thirdparty/libpng/pngdebug.h",
	"thirdparty/libpng/pngerror.c",
	"thirdparty/libpng/pngget.c",
	"thirdparty/libpng/pngmem.c",
	"thirdparty/libpng/pngpread.c",
	"thirdparty/libpng/pngread.c",
	"thirdparty/libpng/pngrio.c",
	"thirdparty/libpng/pngrtran.c",
	"thirdparty/libpng/pngrutil.c",
	"thirdparty/libpng/pngset.c",
	"thirdparty/libpng/pngtrans.c",
	"thirdparty/libpng/pngwio.c",
	"thirdparty/libpng/pngwrite.c",
	"thirdparty/libpng/pngwtran.c",
	"thirdparty/libpng/pngwutil.c"
}

--
-- GLEW
--

glew_public = {
	"thirdparty/glew/include/GL/glew.h",
	"thirdparty/glew/include/GL/wglew.h"
}

glew_sources = {
	"thirdparty/glew/src/glew.c"
}

--
-- XAtlas
--

xatlas_public = {
	"thirdparty/xatlas/xatlas.h",
}

xatlas_sources = {
	"thirdparty/xatlas/xatlas.cpp",
}

--
-- UVAtlas
--

uvatlas_public = {
	"thirdparty/UVAtlas/UVAtlas/inc/UVAtlas.h",
}

uvatlas_sources = {
	"thirdparty/UVAtlas/UVAtlas/geodesics/*.cpp",
	"thirdparty/UVAtlas/UVAtlas/geodesics/*.h",
	"thirdparty/UVAtlas/UVAtlas/isochart/*.cpp",
	"thirdparty/UVAtlas/UVAtlas/isochart/*.h"
}

--
-- ImGUI
--

imgui_public = {
	"thirdparty/imgui/imgui.h",
	"thirdparty/imgui/imconfig.h"
}

imgui_sources = {
	"thirdparty/imgui/imgui_internal.h",
	"thirdparty/imgui/imgui.cpp",
	"thirdparty/imgui/imgui_demo.cpp",
	"thirdparty/imgui/imgui_draw.cpp",
	"thirdparty/imgui/imgui_tables.cpp",
	"thirdparty/imgui/imgui_widgets.cpp",

	--"thirdparty/imgui/misc/freetype/imgui_freetype.*",

	"thirdparty/imgui/backends/imgui_impl_opengl3.*"
}

--
-- MeshOptimizer
--

meshoptimizer_public = {
	"thirdparty/meshoptimizer/src/meshoptimizer.h"
}

meshoptimizer_sources = {
	"thirdparty/meshoptimizer/src/*.cpp",
}

--
-- freetype
--

freetype_public_headers = {
	"thirdparty/freetype/include/ft2build.h",
	"thirdparty/freetype/include/freetype/*.h"
}

freetype_config_headers = {
	"thirdparty/freetype/include/freetype/config/*.h"
}

freetype_private_headers = {
	"thirdparty/freetype/include/freetype/internal/*.h"
}

freetype_sources = {
	-- base
	"thirdparty/freetype/src/autofit/autofit.c",
	"thirdparty/freetype/src/base/ftbase.c",
	"thirdparty/freetype/src/base/ftbbox.c",
	"thirdparty/freetype/src/base/ftbdf.c",
	"thirdparty/freetype/src/base/ftbitmap.c",
	"thirdparty/freetype/src/base/ftcid.c",
	"thirdparty/freetype/src/base/ftfstype.c",
	"thirdparty/freetype/src/base/ftgasp.c",
	"thirdparty/freetype/src/base/ftglyph.c",
	"thirdparty/freetype/src/base/ftgxval.c",
	"thirdparty/freetype/src/base/ftinit.c",
	"thirdparty/freetype/src/base/ftmm.c",
	"thirdparty/freetype/src/base/ftotval.c",
	"thirdparty/freetype/src/base/ftpatent.c",
	"thirdparty/freetype/src/base/ftpfr.c",
	"thirdparty/freetype/src/base/ftstroke.c",
	"thirdparty/freetype/src/base/ftsynth.c",
	"thirdparty/freetype/src/base/fttype1.c",
	"thirdparty/freetype/src/base/ftwinfnt.c",
	"thirdparty/freetype/src/bdf/bdf.c",
	"thirdparty/freetype/src/bzip2/ftbzip2.c",
	"thirdparty/freetype/src/cache/ftcache.c",
	"thirdparty/freetype/src/cff/cff.c",
	"thirdparty/freetype/src/cid/type1cid.c",
	"thirdparty/freetype/src/gzip/ftgzip.c",
	"thirdparty/freetype/src/lzw/ftlzw.c",
	"thirdparty/freetype/src/pcf/pcf.c",
	"thirdparty/freetype/src/pfr/pfr.c",
	"thirdparty/freetype/src/psaux/psaux.c",
	"thirdparty/freetype/src/pshinter/pshinter.c",
	"thirdparty/freetype/src/psnames/psnames.c",
	"thirdparty/freetype/src/raster/raster.c",
	"thirdparty/freetype/src/sdf/sdf.c",
	"thirdparty/freetype/src/sfnt/sfnt.c",
	"thirdparty/freetype/src/smooth/smooth.c",
	"thirdparty/freetype/src/truetype/truetype.c",
	"thirdparty/freetype/src/type1/type1.c",
	"thirdparty/freetype/src/type42/type42.c",
	"thirdparty/freetype/src/winfonts/winfnt.c",

	"thirdparty/freetype/builds/windows/ftsystem.c",
	"thirdparty/freetype/builds/windows/ftdebug.c"
}

--
-- Jolt Physics
--

joltphysics_sources = {
	"thirdparty/JoltPhysics/Jolt/AABBTree/AABBTreeBuilder.cpp",
	"thirdparty/JoltPhysics/Jolt/AABBTree/AABBTreeBuilder.h",
	"thirdparty/JoltPhysics/Jolt/AABBTree/AABBTreeToBuffer.h",
	"thirdparty/JoltPhysics/Jolt/AABBTree/NodeCodec/NodeCodecQuadTreeHalfFloat.h",
	"thirdparty/JoltPhysics/Jolt/AABBTree/TriangleCodec/TriangleCodecIndexed8BitPackSOA4Flags.h",
	"thirdparty/JoltPhysics/Jolt/Core/AlignedAllocator.h",
	"thirdparty/JoltPhysics/Jolt/Core/Atomics.h",
	"thirdparty/JoltPhysics/Jolt/Core/ByteBuffer.h",
	"thirdparty/JoltPhysics/Jolt/Core/Color.cpp",
	"thirdparty/JoltPhysics/Jolt/Core/Color.h",
	"thirdparty/JoltPhysics/Jolt/Core/Core.h",
	"thirdparty/JoltPhysics/Jolt/Core/Factory.cpp",
	"thirdparty/JoltPhysics/Jolt/Core/Factory.h",
	"thirdparty/JoltPhysics/Jolt/Core/FixedSizeFreeList.h",
	"thirdparty/JoltPhysics/Jolt/Core/FixedSizeFreeList.inl",
	"thirdparty/JoltPhysics/Jolt/Core/FPControlWord.h",
	"thirdparty/JoltPhysics/Jolt/Core/FPException.h",
	"thirdparty/JoltPhysics/Jolt/Core/FPFlushDenormals.h",
	"thirdparty/JoltPhysics/Jolt/Core/HashCombine.h",
	"thirdparty/JoltPhysics/Jolt/Core/IssueReporting.cpp",
	"thirdparty/JoltPhysics/Jolt/Core/IssueReporting.h",
	"thirdparty/JoltPhysics/Jolt/Core/JobSystem.h",
	"thirdparty/JoltPhysics/Jolt/Core/JobSystem.inl",
	"thirdparty/JoltPhysics/Jolt/Core/JobSystemThreadPool.cpp",
	"thirdparty/JoltPhysics/Jolt/Core/JobSystemThreadPool.h",
	"thirdparty/JoltPhysics/Jolt/Core/LinearCurve.cpp",
	"thirdparty/JoltPhysics/Jolt/Core/LinearCurve.h",
	"thirdparty/JoltPhysics/Jolt/Core/LockFreeHashMap.h",
	"thirdparty/JoltPhysics/Jolt/Core/LockFreeHashMap.inl",
	--"thirdparty/JoltPhysics/Jolt/Core/Memory.cpp", -- Replaced with our own functions in our core
	"thirdparty/JoltPhysics/Jolt/Core/Memory.h",
	"thirdparty/JoltPhysics/Jolt/Core/Mutex.h",
	"thirdparty/JoltPhysics/Jolt/Core/MutexArray.h",
	"thirdparty/JoltPhysics/Jolt/Core/NonCopyable.h",
	"thirdparty/JoltPhysics/Jolt/Core/Profiler.cpp",
	"thirdparty/JoltPhysics/Jolt/Core/Profiler.h",
	"thirdparty/JoltPhysics/Jolt/Core/Profiler.inl",
	"thirdparty/JoltPhysics/Jolt/Core/Reference.h",
	"thirdparty/JoltPhysics/Jolt/Core/Result.h",
	"thirdparty/JoltPhysics/Jolt/Core/RTTI.cpp",
	"thirdparty/JoltPhysics/Jolt/Core/RTTI.h",
	"thirdparty/JoltPhysics/Jolt/Core/StaticArray.h",
	"thirdparty/JoltPhysics/Jolt/Core/StreamIn.h",
	"thirdparty/JoltPhysics/Jolt/Core/StreamOut.h",
	"thirdparty/JoltPhysics/Jolt/Core/StreamWrapper.h",
	"thirdparty/JoltPhysics/Jolt/Core/StringTools.cpp",
	"thirdparty/JoltPhysics/Jolt/Core/StringTools.h",
	"thirdparty/JoltPhysics/Jolt/Core/TempAllocator.h",
	"thirdparty/JoltPhysics/Jolt/Core/TickCounter.cpp",
	"thirdparty/JoltPhysics/Jolt/Core/TickCounter.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/AABox.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/AABox4.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/ClipPoly.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/ClosestPoint.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/ConvexHullBuilder.cpp",
	"thirdparty/JoltPhysics/Jolt/Geometry/ConvexHullBuilder.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/ConvexHullBuilder2D.cpp",
	"thirdparty/JoltPhysics/Jolt/Geometry/ConvexHullBuilder2D.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/ConvexSupport.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/Ellipse.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/EPAConvexHullBuilder.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/EPAPenetrationDepth.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/GJKClosestPoint.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/IndexedTriangle.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/Indexify.cpp",
	"thirdparty/JoltPhysics/Jolt/Geometry/Indexify.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/MortonCode.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/OrientedBox.cpp",
	"thirdparty/JoltPhysics/Jolt/Geometry/OrientedBox.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/Plane.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/RayAABox.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/RayAABox8.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/RayCapsule.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/RayCylinder.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/RaySphere.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/RayTriangle.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/RayTriangle8.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/Sphere.h",
	"thirdparty/JoltPhysics/Jolt/Geometry/Triangle.h",
	"thirdparty/JoltPhysics/Jolt/Jolt.h",
	"thirdparty/JoltPhysics/Jolt/Math/DVec3.h",
	"thirdparty/JoltPhysics/Jolt/Math/DVec3.inl",
	"thirdparty/JoltPhysics/Jolt/Math/EigenValueSymmetric.h",
	"thirdparty/JoltPhysics/Jolt/Math/FindRoot.h",
	"thirdparty/JoltPhysics/Jolt/Math/Float2.h",
	"thirdparty/JoltPhysics/Jolt/Math/Float3.h",
	"thirdparty/JoltPhysics/Jolt/Math/Float4.h",
	"thirdparty/JoltPhysics/Jolt/Math/GaussianElimination.h",
	"thirdparty/JoltPhysics/Jolt/Math/HalfFloat.h",
	"thirdparty/JoltPhysics/Jolt/Math/Mat44.h",
	"thirdparty/JoltPhysics/Jolt/Math/Mat44.inl",
	"thirdparty/JoltPhysics/Jolt/Math/Math.h",
	"thirdparty/JoltPhysics/Jolt/Math/MathTypes.h",
	"thirdparty/JoltPhysics/Jolt/Math/Matrix.h",
	"thirdparty/JoltPhysics/Jolt/Math/Quat.h",
	"thirdparty/JoltPhysics/Jolt/Math/Quat.inl",
	"thirdparty/JoltPhysics/Jolt/Math/Swizzle.h",
	"thirdparty/JoltPhysics/Jolt/Math/UVec4.cpp",
	"thirdparty/JoltPhysics/Jolt/Math/UVec4.h",
	"thirdparty/JoltPhysics/Jolt/Math/UVec4.inl",
	"thirdparty/JoltPhysics/Jolt/Math/UVec8.h",
	"thirdparty/JoltPhysics/Jolt/Math/UVec8.inl",
	"thirdparty/JoltPhysics/Jolt/Math/Vec3.cpp",
	"thirdparty/JoltPhysics/Jolt/Math/Vec3.h",
	"thirdparty/JoltPhysics/Jolt/Math/Vec3.inl",
	"thirdparty/JoltPhysics/Jolt/Math/Vec4.h",
	"thirdparty/JoltPhysics/Jolt/Math/Vec4.inl",
	"thirdparty/JoltPhysics/Jolt/Math/Vec8.h",
	"thirdparty/JoltPhysics/Jolt/Math/Vec8.inl",
	"thirdparty/JoltPhysics/Jolt/Math/Vector.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/GetPrimitiveTypeOfType.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStream.cpp",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStream.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamBinaryIn.cpp",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamBinaryIn.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamBinaryOut.cpp",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamBinaryOut.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamIn.cpp",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamIn.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamOut.cpp",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamOut.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamTextIn.cpp",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamTextIn.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamTextOut.cpp",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamTextOut.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/ObjectStreamTypes.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/SerializableAttribute.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/SerializableAttributeEnum.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/SerializableAttributeTyped.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/SerializableObject.cpp",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/SerializableObject.h",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/TypeDeclarations.cpp",
	"thirdparty/JoltPhysics/Jolt/ObjectStream/TypeDeclarations.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/Body.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/Body.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/Body.inl",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyAccess.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyAccess.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyActivationListener.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyCreationSettings.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyCreationSettings.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyFilter.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyID.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyInterface.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyInterface.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyLock.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyLockInterface.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyLockMulti.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyManager.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyManager.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/BodyPair.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/MassProperties.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/MassProperties.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/MotionProperties.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/MotionProperties.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/MotionProperties.inl",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/MotionQuality.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Body/MotionType.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Character/Character.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Character/Character.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/AABoxCast.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/ActiveEdgeMode.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/ActiveEdges.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BackFaceMode.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/BroadPhase.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/BroadPhase.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/BroadPhaseBruteForce.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/BroadPhaseBruteForce.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/BroadPhaseLayer.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/BroadPhaseQuadTree.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/BroadPhaseQuadTree.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/BroadPhaseQuery.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/QuadTree.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/BroadPhase/QuadTree.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CastConvexVsTriangles.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CastConvexVsTriangles.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CastSphereVsTriangles.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CastSphereVsTriangles.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CastResult.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollectFacesMode.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollideConvexVsTriangles.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollideConvexVsTriangles.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollidePointResult.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollideShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollideSphereVsTriangles.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollideSphereVsTriangles.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollisionCollector.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollisionCollectorImpl.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollisionDispatch.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollisionDispatch.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollisionGroup.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/CollisionGroup.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/ContactListener.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/GroupFilter.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/GroupFilter.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/GroupFilterTable.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/GroupFilterTable.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/ManifoldBetweenTwoFaces.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/ManifoldBetweenTwoFaces.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/NarrowPhaseQuery.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/NarrowPhaseQuery.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/NarrowPhaseStats.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/NarrowPhaseStats.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/ObjectLayer.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/PhysicsMaterial.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/PhysicsMaterial.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/PhysicsMaterialSimple.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/PhysicsMaterialSimple.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/RayCast.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/BoxShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/BoxShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/CapsuleShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/CapsuleShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/CompoundShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/CompoundShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/CompoundShapeVisitors.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/ConvexHullShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/ConvexHullShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/ConvexShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/ConvexShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/CylinderShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/CylinderShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/DecoratedShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/DecoratedShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/GetTrianglesContext.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/HeightFieldShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/HeightFieldShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/MeshShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/MeshShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/MutableCompoundShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/MutableCompoundShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/OffsetCenterOfMassShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/OffsetCenterOfMassShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/PolyhedronSubmergedVolumeCalculator.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/RotatedTranslatedShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/RotatedTranslatedShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/ScaledShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/ScaledShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/ScaleHelpers.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/Shape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/Shape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/SphereShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/SphereShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/StaticCompoundShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/StaticCompoundShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/SubShapeID.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/SubShapeIDPair.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/TaperedCapsuleShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/TaperedCapsuleShape.gliffy",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/TaperedCapsuleShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/TriangleShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/Shape/TriangleShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/ShapeCast.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/ShapeFilter.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/SortReverseAndStore.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/TransformedShape.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Collision/TransformedShape.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConeConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConeConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/Constraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/Constraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintManager.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintManager.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintPart/AngleConstraintPart.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintPart/AxisConstraintPart.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintPart/DualAxisConstraintPart.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintPart/HingeRotationConstraintPart.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintPart/PointConstraintPart.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintPart/RotationEulerConstraintPart.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintPart/RotationQuatConstraintPart.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintPart/SpringPart.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ConstraintPart/SwingTwistConstraintPart.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ContactConstraintManager.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/ContactConstraintManager.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/DistanceConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/DistanceConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/FixedConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/FixedConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/HingeConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/HingeConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/MotorSettings.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/MotorSettings.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/PathConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/PathConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/PathConstraintPath.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/PathConstraintPath.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/PathConstraintPathHermite.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/PathConstraintPathHermite.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/PointConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/PointConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/SixDOFConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/SixDOFConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/SliderConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/SliderConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/SwingTwistConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/SwingTwistConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/TwoBodyConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Constraints/TwoBodyConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/EActivation.h",
	"thirdparty/JoltPhysics/Jolt/Physics/IslandBuilder.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/IslandBuilder.h",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsLock.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsLock.h",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsScene.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsScene.h",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsSettings.h",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsStepListener.h",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsSystem.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsSystem.h",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsUpdateContext.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/PhysicsUpdateContext.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Ragdoll/Ragdoll.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Ragdoll/Ragdoll.h",
	"thirdparty/JoltPhysics/Jolt/Physics/StateRecorder.h",
	"thirdparty/JoltPhysics/Jolt/Physics/StateRecorderImpl.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/StateRecorderImpl.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/TrackedVehicleController.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/TrackedVehicleController.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleAntiRollBar.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleAntiRollBar.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleCollisionTester.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleCollisionTester.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleConstraint.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleConstraint.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleController.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleController.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleDifferential.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleDifferential.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleEngine.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleEngine.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleTrack.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleTrack.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleTransmission.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/VehicleTransmission.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/Wheel.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/Wheel.h",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/WheeledVehicleController.cpp",
	"thirdparty/JoltPhysics/Jolt/Physics/Vehicle/WheeledVehicleController.h",
	"thirdparty/JoltPhysics/Jolt/RegisterTypes.cpp",
	"thirdparty/JoltPhysics/Jolt/RegisterTypes.h",
	"thirdparty/JoltPhysics/Jolt/Renderer/DebugRenderer.cpp",
	"thirdparty/JoltPhysics/Jolt/Renderer/DebugRenderer.h",
	"thirdparty/JoltPhysics/Jolt/Renderer/DebugRendererPlayback.cpp",
	"thirdparty/JoltPhysics/Jolt/Renderer/DebugRendererPlayback.h",
	"thirdparty/JoltPhysics/Jolt/Renderer/DebugRendererRecorder.cpp",
	"thirdparty/JoltPhysics/Jolt/Renderer/DebugRendererRecorder.h",
	"thirdparty/JoltPhysics/Jolt/Skeleton/SkeletalAnimation.cpp",
	"thirdparty/JoltPhysics/Jolt/Skeleton/SkeletalAnimation.h",
	"thirdparty/JoltPhysics/Jolt/Skeleton/Skeleton.cpp",
	"thirdparty/JoltPhysics/Jolt/Skeleton/Skeleton.h",
	"thirdparty/JoltPhysics/Jolt/Skeleton/SkeletonPose.cpp",
	"thirdparty/JoltPhysics/Jolt/Skeleton/SkeletonPose.h",
	"thirdparty/JoltPhysics/Jolt/TriangleGrouper/TriangleGrouper.h",
	"thirdparty/JoltPhysics/Jolt/TriangleGrouper/TriangleGrouperClosestCentroid.cpp",
	"thirdparty/JoltPhysics/Jolt/TriangleGrouper/TriangleGrouperClosestCentroid.h",
	"thirdparty/JoltPhysics/Jolt/TriangleGrouper/TriangleGrouperMorton.cpp",
	"thirdparty/JoltPhysics/Jolt/TriangleGrouper/TriangleGrouperMorton.h",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitter.cpp",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitter.h",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterBinning.cpp",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterBinning.h",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterFixedLeafSize.cpp",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterFixedLeafSize.h",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterLongestAxis.cpp",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterLongestAxis.h",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterMean.cpp",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterMean.h",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterMorton.cpp",
	"thirdparty/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterMorton.h",
	
	"thirdparty/JoltPhysics/Jolt/Jolt.cmake",
	"thirdparty/JoltPhysics/Jolt/Jolt.natvis",
	"thirdparty/JoltPhysics/Jolt/pch.cpp"
}
